# Generated by Django 3.2.9 on 2021-11-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=15, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insp', models.DateField(verbose_name='Data da Inspeção')),
                ('horario', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 1), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], verbose_name='Horario da Inspeção')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
